services:
  backend:
    image: api:1.1
    volumes:
      - ./FileStorage:/FileStorage
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/moodle_DB
      - DB_User=postgres
      - DB_Password=123